### ISSUE TITLE
Consets object null using nodejs

### ISSUE THREAD

**Issue by fabiobacchi** [contactlab/contacthub-sdk-nodejs#75]
we are fancing same issue on adding information in the proprety consents using the addcustomer/Patchcustomer function, below the payload sent.

It works properly using API service but using nodejs the property consents is null:

{
               "nodeId": "xxx",
               "enabled": true,
               "base": {
                              "firstName": "name",
                              "lastName": "surname",
                              "contacts": {
                                            "email": "test@domain.com",
                                            "phone": "+393471234567"
                              },
                              "address": {
                                            "country": "IT"
                              }
               },
               "extended": {
                              "jobTitle": "Owner / General Manager / CEO",
                              "department": "Business Intelligence",
                              "company": "xxxxxx",
                              "sector": "OTR - System Integrator",
                              "preferences": {
                                            "read_privacy": "true",
                                            "promotional": "false",
                                            "profiling": "false"
                              },
                              "touchpoint": "webinar",
                              "lang": "it",
                              "emailVerified": false
               },
               "tags": {
               },
               "consents": {
                              "disclaimer": {
                                            "date": "2018-05-25T00:00:00.000Z",
                                            "version": "1-2018"
                              },
                              "marketing": {
                                            "traditional": {
                                                           "telephonic": {
                                                                          "status": false
                                                           },
                                                           "papery": {
                                                                          "status": false
                                                           }
                                            },
                                            "automatic": {
                                                           "sms": {
                                                                          "status": false
                                                           },
                                                           "email": {
                                                                          "status": true
                                                           },
                                                           "push": {
                                                                          "status": false
                                                           },
                                                           "im": {
                                                                          "status": false
                                                           }
                                            }
                              },
                              "profiling": {
                                            "classic": {
                                                           "status": false
                                            },
                                            "online": {
                                                           "status": false
                                            }
                              }
               }
}

**Comment by dhinus** [comment]
@fabiobacchi thanks for the bug report. I'll look into this tomorrow.

**Comment by dhinus** [comment]
@fabiobacchi I opened a pull request that should fix the issue. Please have a look.
